### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by weijia-cheng** [CalendulaAsteraceae/georgette-heyer_the-transformation-of-philip-jettan#1]
# Lint

There are only a few lint errors (most of which are semantics/italicization issues) so I’ll just include this as part of the review, but note that we usually ask producers to run lint and address all issues it raises before proceeding to the review.

- [x] `chapter-3`: The chapter title needs to be renamed to match the output of `se titlecase`. Also make sure to run `se build-title` and `se build-toc` after you’ve changed the title.

# Spelling

- [x] You should accept the spelling modernization of (a propos -> apropos) which should go into an [Editorial] commit.

# Semantics

- [x] You should undo the changes in a8703dd9b8b6b1180e454b2d576daaf31f2895b4 and the subsequent changes involving subchapters. `z3998:subchapter` is generally reserved for *structural* divisions, i.e. when a chapter is divided into subchapters that have their own headings and go into the table of contents. The original structure where the unnamed divisions within the chapter are marked by `<hr/>`s is fine. Also, we don’t want to use custom styling to change the appearance of the `<hr/>`. In general we keep to default SE styling as much as possible.
- [x] In the places where you used `z3998:poem`, you should use `z3998:verse` instead because none of them are complete poems. (You will want to update the corresponding CSS as well.)
- [x] The second verse block in chapter-8 (beginning with “Enfin”) needs to be marked as French.
- [x] The letters in chapter 10, 13, and any others I’ve missed need to be in a blockquote and follow the full letter styling rules given in [7.7](https://standardebooks.org/manual/1.7.0/7-high-level-structural-patterns#7.7).
- [ ] You should remove the italics on these loanwords which are in Merriam-Webster (this is also flagged by lint):

* protégé
* chef
* apropos (this would be after you do the spelling modernization in an [Editorial] commit)
* coup de grâce
* savoir faire
* rondeau
* cuisine
* ménage
* blasé
* affaire(s)
* soirées

- [x] Change all instances of `<abbr xml:lang="fr">M.</abbr>` to `<abbr>M.</abbr>`. “Monsieur” is also a loanword in English so we don’t treat `M.` as a “French” abbreviation.
- [x] You have a mix of “m’sieur” being wrapped in `<i xml:lang="fr">` and `<span xml:lang="fr">`. I think when it’s standing by itself (not being used within a larger French-language phrase) you can remove the italics/span because it’s just “monsieur” (a word in Merriam-Webster) with a contraction/elision. Similar deal with “m’sieu’.”
- [x] Besides “m’sieur” above, you have wrapped several freestanding English loanwords with `<span xml:lang="fr">` where this is not necessary:

* Marquis
* Mademoiselle
* Madame

You’ve also wrapped several names with `<span xml:lang="fr">` that seem pretty unambiguously French to me, in which case we don’t need the semantics. This is more of a judgment call and isn’t wrong per se, but you can save some time in the future by not having to tag names like “François” and “Philippe” which are clearly French and don’t have alternative English pronunciations (e.g. “Jean” having the tag is helpful).

# Typography

- [x] `chapter-9`: You have an instance of `ve-ry` where a hyphen is inserted in the middle of the word to indicate that it is being drawn out. Per [8.7.7.6](https://standardebooks.org/manual/1.7.0/8-typography#8.7.7.6) you want to use a non-break hyphen character `‑` rather than the normal hyphen.
- [x] You should do the same for `Cle-one` in chapter 17.

# Metadata

- [x] Is there any reason you aren’t using [this 1923 page scan](https://archive.org/details/in.ernet.dli.2015.148805) as the backing source? At first glance it looks to be the same text as the transcription, but you’d be the expert on that, obviously. If this is the same text we should prefer these scans, because it’s definitively out of copyright and has a full view (which might matter soon given the legal ordeal the Internet Archive is being put through...) If/when you change this, you’re going to need to update the colophon and imprint too.

# CSS

- [x] `[epub|type~="z3998:poem"][xml|lang]` selector should be `blockquote[xml|lang]` per [8.2.9.6](https://standardebooks.org/manual/1.7.0/8-typography#8.2.9.6).

# Colophpn

- [x] The anchor for “Mariah C. Laugesen” shouldn’t have a personal name semantic (but your middle initial needs to be in an abbr with a semantic, see [8.10.4](https://standardebooks.org/manual/1.7.0/8-typography#8.10.4)).
- [x] Initials of “J. C. Leyendecker” needs semantics too.

# Images

- [x] `se build-images` changes `cover.source.jpg`. I don’t exactly know what this is changing, but we should accept the changes.

# Commit History

- [x] a46a5ce5e4d29113f5012bc6de4c989bc20dac5c: This is not editorial; it’s just a styling/typography fix. You can remove the [Editorial] tag in rebase (let me know if you need more detailed instructions on how to do that, since I know not everyone who contributes to SE is super well-versed in that side of git).

**Comment by CalendulaAsteraceae** [comment]
Thank you! Responses below.

# Lint

> `chapter-3`: The chapter title needs to be renamed to match the output of `se titlecase`. Also make sure to run `se build-title` and `se build-toc` after you’ve changed the title.

`se titlecase` doesn't change the capitalization of "Mr. Bancroft Brings Trouble into Little Fittledean", and this seems correct since I don't think that prepositions are supposed to be capitalized in titles.

# Metadata

> Is there any reason you aren’t using [this 1923 page scan](https://archive.org/details/in.ernet.dli.2015.148805) as the backing source? At first glance it looks to be the same text as the transcription, but you’d be the expert on that, obviously. If this is the same text we should prefer these scans, because it’s definitively out of copyright and has a full view (which might matter soon given the legal ordeal the Internet Archive is being put through...) If/when you change this, you’re going to need to update the colophon and imprint too.

This scan has a falsified colophon, but it is a scan of _Powder and Patch_, which was first published in 1930 by William Heinemann and removed Chapter 20.

# Spelling

> You should accept the spelling modernization of (a propos -> apropos) which should go into an [Editorial] commit.

My read of that scene is that the character is speaking French (which happens a lot in this book). However, if it's French it should have an accent on the A (à propos) so I've added that in an [Editorial] commit. See Semantics below.

# Semantics

> You should remove the italics on these loanwords which are in Merriam-Webster (this is also flagged by lint):

* protégé
* chef
* apropos (this would be after you do the spelling modernization in an [Editorial] commit)
* coup de grâce
* savoir faire
* rondeau
* cuisine
* ménage
* blasé
* affaire(s)
* soirées

The amount that characters in this novel speak French and use French loanwords is an important thematic element/point of characterization, so I'd rather leave these as they are to make it clear that they are being used as French loanwords.

# Commit History

> a46a5ce5e4d29113f5012bc6de4c989bc20dac5c: This is not editorial; it’s just a styling/typography fix. You can remove the [Editorial] tag in rebase (let me know if you need more detailed instructions on how to do that, since I know not everyone who contributes to SE is super well-versed in that side of git).

I do need more detailed instructions. I tried using `git rebase -i HEAD~60` and this looked like it was probably doing the right thing but I couldn't figure out how to use the interface.

**Comment by weijia-cheng** [comment]
> se titlecase doesn't change the capitalization of "Mr. Bancroft Brings Trouble into Little Fittledean", and this seems correct since I don't think that prepositions are supposed to be capitalized in titles.

Are you sure? It changes the capitalization for me on the latest version:

```
wcheng@pop-os:~/git/georgette-heyer_the-transformation-of-philip-jettan$ se titlecase "Mr. Bancroft Brings Trouble into Little Fittledean"
Mr. Bancroft Brings Trouble Into Little Fittledean
```

`se titlecase` establishes our title capitalization style, so we should make the change.

For the rebase, start with executing this command:

```
git rebase -i a46a5ce5e4d29113f5012bc6de4c989bc20dac5c~
```

This begins an interactive rebase from that commit onwards. Then you'll see this interface:

```
pick a46a5ce [Editorial] move period inside italics
pick 11ad9a8 Remove unused CSS selector
pick 9b79bbc declare XML namespace
pick 2aecd72 Correct class for the Rambler
pick 25d0a6f Chapter 8 poem: space line at 18em
pick 44f2a30 Add missing <hr/>
pick a8703dd Mark the larger section breaks as subchapters and add style to the hr between subchapters
pick 1418b8d Add ids to subchapter sections
pick f36c7a0 Correct order of subchapter section properties
pick 61acce6 Simplify readme
pick 61fb743 Make the hr dividing subchapters wider
pick 8339e51 Correct title on title page
pick b53a179 Create halftitlepage.xhtml
pick 43b8112 Clean half-title page
pick 7cdcdb7 Revert "Correct title on title page"
pick c8e2a9b Update manifest and spine
pick dec3045 Update toc.xhtml
pick 115f47f Add cover image
pick b2e8de6 Add metadata to content.opf
pick dfa6e98 Add transcriber sort
pick 80efa25 Update metadata of cover source image
pick 31cfcd7 Add description
pick 842a0df Add producer homepage
pick 5c5bd4e Complete the imprint and colophon
pick bfb9287 Run typogrify
pick 1dc5dcc Add description draft
pick 984f173 remove epub:type="se:name.publication.book" from content.opf
pick 8bfcf81 Clean content.opf
pick 6d918c3 add to long description draft
pick 64028f4 add to long description
pick a385ecd "Book" only has two Os
pick 4962803 Add to description draft
pick 354b8d6 Improve short and long description
pick 223119e Add link to Georgette Heyer in long description
pick 880a2e9 And clean the link in the long description
pick 1cb42db Add "romance" to long description
pick 3e9d6cb Remove .gitattributes and README.md
pick b8c2a90 Remove italics from production notes
pick fbd7bec [Editorial] add accent to "à propos"
pick 8af7452 Use z3998:verse instead of z3998:poem
pick e85e263 Add lang tag for French
pick 89945fa Remove lang tags from "<abbr>M.</abbr>"
pick ed1ece8 Remove lang tags from monsieur and variants
pick 6dae7bb Use <em> for an italicized "M’sieur" since it's not usually italicized in the source
pick 3504cde Move the lang tags on "M’sieur Philippe" to just "Philippe"
pick acda939 Remove lang tags from madame
pick bd7f8b1 Also remove lang tags from capitalized Madame
pick bc10eec [Editorial] remove italics from madame
pick c34f2fa Remove lang tags from Mademoiselle
pick 6956003 Remove lang tags from Marquis
pick b73b030 Use non-breaking hyphen for ve‑ry
pick 7d87998 Use non-breaking hyphen for Cle‑one
pick 46bd626 Correct semantics of personal names in colophon
pick 276d1d9 CSS: target italicized poetry with blockquote
pick 3556d18 Update cover.source.jpg
pick 3624c78 [Editorial] reformat letters
pick c699bb3 Remove subchapter markup.
pick ea32e51 Use se clean
pick 0920a88 Clean up letter semantics and CSS
pick e9f06d4 Remove unused class
```

You'll want to change the `pick` in the first line to `reword`, then save the file:

```
reword a46a5ce [Editorial] move period inside italics
pick 11ad9a8 Remove unused CSS selector
pick 9b79bbc declare XML namespace
pick 2aecd72 Correct class for the Rambler
pick 25d0a6f Chapter 8 poem: space line at 18em
pick 44f2a30 Add missing <hr/>
pick a8703dd Mark the larger section breaks as subchapters and add style to the hr between subchapters
pick 1418b8d Add ids to subchapter sections
pick f36c7a0 Correct order of subchapter section properties
pick 61acce6 Simplify readme
pick 61fb743 Make the hr dividing subchapters wider
pick 8339e51 Correct title on title page
pick b53a179 Create halftitlepage.xhtml
pick 43b8112 Clean half-title page
pick 7cdcdb7 Revert "Correct title on title page"
pick c8e2a9b Update manifest and spine
pick dec3045 Update toc.xhtml
pick 115f47f Add cover image
pick b2e8de6 Add metadata to content.opf
pick dfa6e98 Add transcriber sort
pick 80efa25 Update metadata of cover source image
pick 31cfcd7 Add description
pick 842a0df Add producer homepage
pick 5c5bd4e Complete the imprint and colophon
pick bfb9287 Run typogrify
pick 1dc5dcc Add description draft
pick 984f173 remove epub:type="se:name.publication.book" from content.opf
pick 8bfcf81 Clean content.opf
pick 6d918c3 add to long description draft
pick 64028f4 add to long description
pick a385ecd "Book" only has two Os
pick 4962803 Add to description draft
pick 354b8d6 Improve short and long description
pick 223119e Add link to Georgette Heyer in long description
pick 880a2e9 And clean the link in the long description
pick 1cb42db Add "romance" to long description
pick 3e9d6cb Remove .gitattributes and README.md
pick b8c2a90 Remove italics from production notes
pick fbd7bec [Editorial] add accent to "à propos"
pick 8af7452 Use z3998:verse instead of z3998:poem
pick e85e263 Add lang tag for French
pick 89945fa Remove lang tags from "<abbr>M.</abbr>"
pick ed1ece8 Remove lang tags from monsieur and variants
pick 6dae7bb Use <em> for an italicized "M’sieur" since it's not usually italicized in the source
pick 3504cde Move the lang tags on "M’sieur Philippe" to just "Philippe"
pick acda939 Remove lang tags from madame
pick bd7f8b1 Also remove lang tags from capitalized Madame
pick bc10eec [Editorial] remove italics from madame
pick c34f2fa Remove lang tags from Mademoiselle
pick 6956003 Remove lang tags from Marquis
pick b73b030 Use non-breaking hyphen for ve‑ry
pick 7d87998 Use non-breaking hyphen for Cle‑one
pick 46bd626 Correct semantics of personal names in colophon
pick 276d1d9 CSS: target italicized poetry with blockquote
pick 3556d18 Update cover.source.jpg
pick 3624c78 [Editorial] reformat letters
pick c699bb3 Remove subchapter markup.
pick ea32e51 Use se clean
pick 0920a88 Clean up letter semantics and CSS
pick e9f06d4 Remove unused class
```

That will put you into a prompt where you can edit the commit message. Once you do that and save the rebase will finish and you can use `git push --force` to push your rebased commit history to GitHub.

**Comment by CalendulaAsteraceae** [comment]
Oops, I see the problem here. I thought `se titlecase` was one of the commands where you could run it and it would automatically change the headings. When I run `se titlecase "Mr. Bancroft Brings Trouble into Little Fittledean"` I get the same result as you. Updated.

I'm still having trouble with the rebase but I think it would help to have a screen capture so I'll move this part of the discussion to the Google thread.
